### ISSUE TITLE
Right click in chrome will overlap from browser context menu.

### ISSUE THREAD

**Issue by Chris2011** [mimorisuzuko/chain#2]
When I try the browser demo: http://mimorisuzuko.github.io/chain/play/#chain-canvas and I tried out to right click, I see very short the menu from the application and than the browser context menu opens. Tried it with the latest chrome, so this is not working for me.

**Comment by mimorisuzuko** [comment]
Thank you for trying! I updated `/gh-pages` now. Probably, this update does not allow the browser context menu to be opened (on the latest chrome).

**Comment by Chris2011** [comment]
Thx :)
