### ISSUE TITLE
Swtching from chain to code doesn't do anything.

### ISSUE THREAD

**Issue by Chris2011** [mimorisuzuko/chain#3]
My intention to do was to switch to code to write a function like:

``` javascript
var function = test() {

}
```

and I thought, when I switch back to chain, It will parse the code and give me the visual block and vice versa. If so, it doesn't work, in both directions.

**Comment by mimorisuzuko** [comment]
If write a code in plugin, you can use the method, but Chain does not add the visual block. So, after switching back to Chain, you should add `Function Block`.

**Comment by Chris2011** [comment]
Is this possible to parse the outputted code and vice versa? This would be very cool so you can create your workflow in the chain canvas and if you click convert to code or click code, you see the code which was generates from the chain. And if you write code and click generate visual code or switch to visual you see the generated stuff.

**Comment by mimorisuzuko** [comment]
No. Clicking **Code**, you can write **plugin**. So, **Code** does not mean that you can get the code generated from Chain. The code that you write in **Code** isn't converted to `Chain Block` and vice versa. But, you can use the function you declare in **plugin(Code)** as `Function Block`.

**Comment by mimorisuzuko** [comment]
And, you has written the code:

``` javascript
var function = test() {

}
```

It has a syntax error?

**Comment by Chris2011** [comment]
Oh yeah sry, i meaned var test = function()

**Comment by Chris2011** [comment]
Ok I understand the point what it does but a converting to and from would be nice :)

**Comment by mimorisuzuko** [comment]
Inside the system, **Chain Block** is converted to the code and execute it. But, my goal isn't it. Mainly, user builds JavaScript with **Chain Block**. When it is limit that user uses **Chain Block**, user use **plugin(Code)**. So, **plugin(Code)** is assistance. Also, my goal is that user builds all JavaScript with **Chain Block** (without **plugin(Code)**).

**Comment by Chris2011** [comment]
Ok maybe I didn't get the whole idea right but often it is so that developers want Visual help this is what uml does and chain for example, but than they need the code for the Application what comes out and not the Visual thing. It is like the Windows Workflow Foundation where you can Design it or write code. And this is what make sense for me. Chain is only a very nice helping Tool to visualise a Workflow of chaining stuff and so on but the code which comes out is needed for the development. Only my opinion.

**Comment by mimorisuzuko** [comment]
You would like to visualize JavaScript code that you write? It sounds good. But, I don't think that Chain becomes it, sorry...

**Comment by Chris2011** [comment]
and vice versa, as you said, the code what chain created inside the application could be outputted as generated code so someone can take it after he created it via the visual editor. So it should work in both directions.

**Comment by mimorisuzuko** [comment]
Chain can convert visual to the code. But, not reverse.

**Comment by mimorisuzuko** [comment]
Now, Chain convert the block to the code (inside the application). I would like you to understand that its reverse is a future work and to expect Chain.

**Comment by Chris2011** [comment]
Yeah and this converted code you can output it to a new section called "generated" or so. To see the output from the chain. So as I understand that this feature is coming in the future right?

**Comment by mimorisuzuko** [comment]
Yes, I can do it immediately from a programming point of view. But, Chain is under development and I am thinking what to do with Chain now. You would like to wait for addition new section called "generated", sorry.

**Comment by Chris2011** [comment]
Ok, with this info, I'm happy :). Great work btw. :+1:

**Comment by mimorisuzuko** [comment]
Thank you for comment and reading my lousy English.
